export { HomePage } from './HomePage'
export { AboutPage } from './AboutPage'
export { GuidelinesPage } from './GuidelinesPage'
export { LegalPage } from './LegalPage'
export { PrivacyPage } from './PrivacyPage'
export { NotFoundPage } from './NotFoundPage'
